### ISSUE TITLE
[Bug]: create new link with already existed slug, it crashed

### ISSUE THREAD

**Issue by taiqn** [aemzayn/kisalt#14]
### Contact Details

soerx10@gmail.com

### What happened?

A bug happened!

I tested with old known slug, it crashed. Hope you could fix that. Thanks

### Relevant log output

```shell
Application error: a client-side exception has occurred (see the browser console for more information).
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by aemzayn** [comment]
Thanks I will fix it
